USE Champ;

CREATE TABLE MARKS (SUBJECT VARCHAR(30), MARKS INT NOT NULL);

INSERT INTO MARKS (SUBJECT, MARKS)
VALUES ("ENGLISH", 90)

INSERT INTO MARKS (SUBJECT, MARKS)
VALUES ("MATHS", 98)

INSERT INTO MARKS (SUBJECT, MARKS)
VALUES ("COMPUTER SCIENCE", 97)

INSERT INTO MARKS (SUBJECT, MARKS)
VALUES ("HINDI", 99)

INSERT INTO MARKS (SUBJECT, MARKS)
VALUES ("SOCIAL SCIENCE", 89)

-- DELETE COMMANDS

-- DELETE FROM MARKS WHERE SUBJECT = 'SOCIAL SCIENCE';

-- DELETE FROM MARKS WHERE SUBJECT = 'ENGLISH' AND MARKS = 90;

-- DELETE FROM MARKS WHERE SUBJECT = 'MATHS' OR MARKS = 99;

-- DELETE FROM MARKS WHERE MARKS = 97 AND SUBJECT = 'COMPUTER SCIENCE';

SELECT * FROM MARKS