CREATE DATABASE Champ;

USE Champ;

CREATE TABLE DISCORD(NAME VARCHAR(50), ID INT NOT NULL)


INSERT INTO DISCORD(NAME, ID)
VALUES ('Champ', 89)

INSERT INTO DISCORD(NAME, ID)
VALUES('Champ Prime', 74)

INSERT INTO DISCORD(NAME, ID)
VALUES('Champ Canary', 54)

INSERT INTO DISCORD(NAME, ID)
VALUES('Dyno', 54)

INSERT INTO DISCORD(NAME, ID)
VALUES('MEE6', 55)

SELECT * FROM DISCORD