CREATE DATABASE Champ;

USE Champ;

CREATE TABLE DISCORD(NAME VARCHAR(50), ID INT NOT NULL)


INSERT INTO DISCORD(NAME, ID)
VALUES ('Champ', 89)

INSERT INTO DISCORD(NAME, ID)
VALUES('Champ Prime', 74)

INSERT INTO DISCORD(NAME, ID)
VALUES('Champ Canary', 54)

INSERT INTO DISCORD(NAME, ID)
VALUES('Dyno', 54)

INSERT INTO DISCORD(NAME, ID)
VALUES('MEE6', 55)

-- SELECT COMMANDS

-- SELECT * FROM DISCORD

-- SELECT ID FROM DISCORD

-- SELECT NAME FROM DISCORD

-- SELECT * FROM DISCORD WHERE NAME = 'Champ';

-- SELECT * FROM DISCORD WHERE ID = 54;

-- SELECT * FROM DISCORD WHERE ID = NULL;

-- SELECT * FROM DISCORD WHERE NAME = 'Champ' and ID = 89;

-- SELECT * FROM DISCORD WHERE NAME = 'Champ' or ID = 54;

-- SELECT * FROM DISCORD WHERE NOT NAME = 'Champ';

-- SELECT * FROM DISCORD WHERE NOT NAME = 'Champ' and NOT NAME = 'Champ Prime';