USE Champ;

CREATE TABLE CARS (NAME VARCHAR(20), PRICE INT NOT NULL);

INSERT INTO CARS(NAME, PRICE)
VALUES ("BMW", 2500000)

INSERT INTO CARS(NAME, PRICE)
VALUES ("AUDI", 1500000)

INSERT INTO CARS(NAME, PRICE)
VALUES("KIA SELTOS", 2000000)

INSERT INTO CARS(NAME, PRICE)
VALUES("PORSCHE", 5000000)

INSERT INTO CARS(NAME, PRICE)
VALUES("BUGATTI", 19000000)


-- UPDATE COMMANDS


-- UPDATE CARS
-- SET NAME = 'AUDI', PRICE = 1000
-- WHERE NAME = 'BUGATTI'

-- UPDATE CARS SET NAME = 'BUGATTI', PRICE = 400000000 WHERE NAME = 'AUDI'

-- Update CARS SET PRICE = 1000 WHERE NAME = 'BMW'

-- UPDATE CARS SET NAME = 'Lamborghini' WHERE NAME = 'BUGATTI'

SELECT * FROM CARS

