USE Champ;

CREATE TABLE MARKS (SUBJECT VARCHAR(20), MARKS INT NOT NULL);


INSERT INTO MARKS (SUBJECT, MARKS)
VALUES ("COMPUTER SCIENCE", 98)

INSERT INTO MARKS (SUBJECT, MARKS)
VALUES ("SCIENCE", 95)

INSERT INTO MARKS (SUBJECT, MARKS)
VALUES ("MATHS", 92)

INSERT INTO MARKS (SUBJECT, MARKS)
VALUES ("ENGLISH", 99)

INSERT INTO MARKS (SUBJECT, MARKS)
VALUES ("HINDI", 90)

-- UPDATE QUEURY

-- UPDATE MARKS SET MARKS = 99 WHERE SUBJECT = 'GK';

-- UPDATE MARKS SET SUBJECT = 'SOCIAL SCIENCE' WHERE SUBJECT = 'GK' AND MARKS = 99;

-- UPDATE MARKS SET MARKS = 100;

-- UPDATE MARKS SET MARKS = 98 WHERE SUBJECT = 'COMPUTER SCIENCE';

-- UPDATE MARKS SET MARKS = 95 WHERE SUBJECT = 'SCIENCE';

-- UPDATE MARKS SET MARKS = 94 WHERE SUBJECT = 'MATHS';

-- UPDATE MARKS SET MARKS = 92 WHERE SUBJECT = 'ENGLISH';

UPDATE MARKS SET MARKS = 89 WHERE SUBJECT = 'SOCIAL SCIENCE';

SELECT * FROM MARKS